apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Krateo Frontend
  description: Krateo Platformops - Dashboard Frontend
  # Example for optional annotations
  # annotations:
  # github.com/project-slug: backstage/backstage
  # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: contact@krateoplatformops.io
  lifecycle: experimental
